%YAML:1.0

#common parameters
savePath: "/home/heyijia/1TDisk/calibra/txt/"
bag_path: "/home/heyijia/1TDisk/calibra/cl_v2.bag"

scan_topic_name: "/scan"
img_topic_name: "/mynteye/left_rect/image_rect"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 752
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0

projection_parameters:
   fx: 367.049931000148
   fy: 366.94446918887405
   cx: 368.7202381120387
   cy: 241.13814795878562

